### ISSUE TITLE
The top of the readme should explain what's included in the immersion day

### ISSUE THREAD

**Issue by gilinachum** [aristsakpinis93/generative-ai-immersion-day#1]
For example:
Lab 1 - Hosting Large Language Models can be found in the lab1 directory. Start with the notebook gpt-j-notebook-full.ipynb.

Lab 2 - Finetuning Large Language Models can be found in the lab2 directory. Start with the notebook fine-tuning.ipynb.

**Comment by aristsakpinis93** [comment]
@gilinachum incorporated your feedback. Thx for raising!
